kind: pipeline
name: CUGOJ_Tools_Publish

steps:
- name: build&publish
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - echo 'start pack'
  - dotnet pack --output nupkgs
  - echo 'start push'
  - sh ./push.sh
  - echo 'end'


trigger:
  branch:
    - dev
    - main
  event:
    - push